GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ai_agent_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ai_agent_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ai_agent_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO ai_agent_runtime;
REVOKE UPDATE, DELETE ON TABLE public.audit_logs FROM ai_agent_runtime;
