#!/bin/sh

set -eu

output=
input=
while [ "$#" -gt 0 ]; do
  case "$1" in
    --homedir|--pinentry-mode|--passphrase-file|--output)
      option=$1
      [ "$#" -ge 2 ] || exit 2
      if [ "$option" = "--output" ]; then
        output=$2
      fi
      shift 2
      ;;
    --decrypt)
      [ "$#" -ge 2 ] || exit 2
      input=$2
      shift 2
      ;;
    --batch|--yes|--no-tty|--no-symkey-cache)
      shift
      ;;
    *)
      exit 2
      ;;
  esac
done

[ -n "$output" ] && [ -n "$input" ]
cat "$input" >"$output"
