export type SolutionDirectoryNode = {
  label: string;
  key?: string;
  anchor?: string;
  href: string;
  children?: readonly SolutionDirectoryNode[];
};

export const solutionDirectory: readonly SolutionDirectoryNode[] = [
  { label: "解决方案总览", key: "overview", href: "/solutions" },
  {
    label: "通用场景方案",
    key: "common",
    anchor: "solution-scenarios-directory",
    href: "/solutions?view=common#solution-scenarios-directory",
    children: [
      {
        label: "基础设施与模型工程",
        key: "infrastructure",
        href: "/solutions?view=common&category=infrastructure#solution-scenarios-directory",
        children: [
          {
            label: "元启私有化部署方案",
            key: "private-yuanqi",
            anchor: "scene-private-yuanqi",
            href: "/solutions/private-yuanqi#scene-private-yuanqi",
          },
          {
            label: "单机与集群算力规划方案",
            key: "cluster-planning",
            anchor: "scene-cluster-planning",
            href: "/solutions/cluster-planning#scene-cluster-planning",
          },
          {
            label: "算力监控与运行保障方案",
            key: "compute-monitoring",
            anchor: "scene-compute-monitoring",
            href: "/solutions/compute-monitoring#scene-compute-monitoring",
          },
          {
            label: "模型适配、训练与效果验证",
            key: "model-evaluation",
            anchor: "scene-model-evaluation",
            href: "/solutions/model-evaluation#scene-model-evaluation",
          },
          {
            label: "企业模型部署与调用",
            key: "model-deployment",
            anchor: "scene-model-deployment",
            href: "/solutions/model-deployment#scene-model-deployment",
          },
        ],
      },
      {
        label: "知识与数据智能",
        key: "knowledge",
        href: "/solutions?view=common&category=knowledge#solution-scenarios-directory",
        children: [
          {
            label: "企业知识问答与知识服务",
            key: "knowledge-service",
            anchor: "scene-knowledge-service",
            href: "/solutions/knowledge-service#scene-knowledge-service",
          },
          {
            label: "文档理解、知识检索与智能审核",
            key: "document-intelligence",
            anchor: "scene-document-intelligence",
            href: "/solutions/document-intelligence#scene-document-intelligence",
          },
          {
            label: "数据问答、分析与业务洞察",
            key: "data-insight",
            anchor: "scene-data-insight",
            href: "/solutions/data-insight#scene-data-insight",
          },
          {
            label: "非结构化数据处理与业务利用",
            key: "unstructured-data",
            anchor: "scene-unstructured-data",
            href: "/solutions/unstructured-data#scene-unstructured-data",
          },
          {
            label: "企业知识库建设与持续运营",
            key: "knowledge-assets",
            anchor: "scene-knowledge-assets",
            href: "/solutions/knowledge-assets#scene-knowledge-assets",
          },
        ],
      },
      {
        label: "智能体与业务应用",
        key: "agents",
        href: "/solutions?view=common&category=agents#solution-scenarios-directory",
        children: [
          {
            label: "业务流程自动化与智能协同",
            key: "process-automation",
            anchor: "scene-process-automation",
            href: "/solutions/process-automation#scene-process-automation",
          },
          {
            label: "视频内容检索与智能分析",
            key: "video-intelligence",
            anchor: "scene-video-intelligence",
            href: "/solutions/video-intelligence#scene-video-intelligence",
          },
          {
            label: "企业内部智能助手",
            key: "enterprise-assistant",
            anchor: "scene-enterprise-assistant",
            href: "/solutions/enterprise-assistant#scene-enterprise-assistant",
          },
          {
            label: "多智能体协同与复杂任务处理",
            key: "multi-agent",
            anchor: "scene-multi-agent",
            href: "/solutions/multi-agent#scene-multi-agent",
          },
        ],
      },
    ],
  },
  {
    label: "行业解决方案",
    key: "industry",
    anchor: "industry-solutions-list",
    href: "/solutions?view=industry#industry-solutions-list",
    children: [
      {
        label: "政务",
        key: "government",
        href: "/solutions?view=industry&category=government#industry-solutions-list",
        children: [
          {
            label: "政务知识问答与政策服务",
            key: "government-knowledge",
            anchor: "industry-government-knowledge",
            href: "/solutions/government-knowledge#industry-government-knowledge",
          },
          {
            label: "政策公文理解与辅助审核",
            key: "government-document",
            anchor: "industry-government-document",
            href: "/solutions/government-document#industry-government-document",
          },
          {
            label: "政务数据问答与分析",
            key: "government-data",
            anchor: "industry-government-data",
            href: "/solutions/government-data#industry-government-data",
          },
          {
            label: "政务事项流程自动化与协同",
            key: "government-process",
            anchor: "industry-government-process",
            href: "/solutions/government-process#industry-government-process",
          },
        ],
      },
      {
        label: "金融",
        key: "finance",
        href: "/solutions?view=industry&category=finance#industry-solutions-list",
        children: [
          {
            label: "金融制度与产品知识服务",
            key: "finance-knowledge",
            anchor: "industry-finance-knowledge",
            href: "/solutions/finance-knowledge#industry-finance-knowledge",
          },
          {
            label: "金融文档理解与合规辅助审核",
            key: "finance-document",
            anchor: "industry-finance-document",
            href: "/solutions/finance-document#industry-finance-document",
          },
          {
            label: "经营数据问答与业务分析",
            key: "finance-data",
            anchor: "industry-finance-data",
            href: "/solutions/finance-data#industry-finance-data",
          },
          {
            label: "金融客户服务智能助手",
            key: "finance-assistant",
            anchor: "industry-finance-assistant",
            href: "/solutions/finance-assistant#industry-finance-assistant",
          },
        ],
      },
      {
        label: "医疗",
        key: "healthcare",
        href: "/solutions?view=industry&category=healthcare#industry-solutions-list",
        children: [
          {
            label: "医院知识与制度问答",
            key: "healthcare-knowledge",
            anchor: "industry-healthcare-knowledge",
            href: "/solutions/healthcare-knowledge#industry-healthcare-knowledge",
          },
          {
            label: "医疗文档信息提取与辅助审核",
            key: "healthcare-document",
            anchor: "industry-healthcare-document",
            href: "/solutions/healthcare-document#industry-healthcare-document",
          },
          {
            label: "医院运营数据问答与分析",
            key: "healthcare-data",
            anchor: "industry-healthcare-data",
            href: "/solutions/healthcare-data#industry-healthcare-data",
          },
          {
            label: "医院行政流程自动化与协同",
            key: "healthcare-process",
            anchor: "industry-healthcare-process",
            href: "/solutions/healthcare-process#industry-healthcare-process",
          },
        ],
      },
      {
        label: "企业智能化",
        key: "enterprise",
        href: "/solutions?view=industry&category=enterprise#industry-solutions-list",
        children: [
          {
            label: "企业内部知识助手",
            key: "enterprise-knowledge",
            anchor: "industry-enterprise-knowledge",
            href: "/solutions/enterprise-knowledge#industry-enterprise-knowledge",
          },
          {
            label: "企业经营数据分析与洞察",
            key: "enterprise-data",
            anchor: "industry-enterprise-data",
            href: "/solutions/enterprise-data#industry-enterprise-data",
          },
          {
            label: "企业文档理解与智能审核",
            key: "enterprise-document",
            anchor: "industry-enterprise-document",
            href: "/solutions/enterprise-document#industry-enterprise-document",
          },
          {
            label: "企业流程自动化与智能协同",
            key: "enterprise-process",
            anchor: "industry-enterprise-process",
            href: "/solutions/enterprise-process#industry-enterprise-process",
          },
          {
            label: "多智能体复杂任务处理",
            key: "enterprise-multi-agent",
            anchor: "industry-enterprise-multi-agent",
            href: "/solutions/enterprise-multi-agent#industry-enterprise-multi-agent",
          },
        ],
      },
    ],
  },
  {
    label: "实践案例",
    key: "cases",
    anchor: "practice-cases-hero",
    href: "/solutions?view=cases#practice-cases-hero",
    children: [
      {
        label: "按行业查看",
        key: "case-industry",
        anchor: "practice-cases-list",
        href: "/solutions?view=cases&mode=industry#practice-cases-list",
        children: [
          {
            label: "案例详情结构占位（待授权案例）",
            key: "case-pending-enterprise-knowledge",
            anchor: "case-pending-enterprise-knowledge",
            href: "/solutions/case-pending-enterprise-knowledge#case-pending-enterprise-knowledge",
          },
        ],
      },
      {
        label: "按业务场景查看",
        key: "case-scenario",
        anchor: "practice-cases-list",
        href: "/solutions?view=cases&mode=scenario#practice-cases-list",
        children: [
          {
            label: "案例详情结构占位（待授权案例）",
            key: "case-pending-enterprise-knowledge",
            anchor: "case-pending-enterprise-knowledge",
            href: "/solutions/case-pending-enterprise-knowledge#case-pending-enterprise-knowledge",
          },
        ],
      },
    ],
  },
];

export const solutionOverviewContent = {
  hero: {
    eyebrow: "解决方案总览｜从业务问题出发",
    title: "面向企业实际业务问题的 AI 解决方案",
    lead: "围绕企业知识服务、数据分析、文档处理、流程协同和智能应用建设，组合元启平台的算力、模型、知识与智能体能力，帮助企业完成从能力建设到业务应用落地。",
    problemTitle: "您希望解决什么问题？",
    problems: [
      ["企业知识如何高效利用", "overview-scene-knowledge"],
      ["业务数据如何自然语言查询", "overview-scene-data"],
      ["复杂文档如何理解与审核", "overview-scene-document"],
      ["重复业务流程如何自动执行", "overview-scene-process"],
      ["AI 能力如何形成可用业务应用", "overview-scene-assistant"],
    ],
    actions: [
      ["查看通用场景方案", "/solutions#solution-common-scenes"],
      ["查看行业解决方案", "/solutions#solution-industries-overview"],
      ["查看实践案例", "/solutions?view=cases#practice-cases-hero"],
    ],
    map: {
      label: "解决方案关系图素材槽位",
      title: "从业务问题到业务成果",
      columns: [
        [
          "业务问题",
          "知识利用",
          "数据查询",
          "文档处理",
          "流程协同",
          "智能应用建设",
        ],
        [
          "华鲲能力组合",
          "算力与运行环境",
          "模型能力",
          "企业知识与数据",
          "智能体与流程编排",
          "应用发布与系统集成",
        ],
        [
          "业务应用与成果",
          "企业知识服务",
          "数据分析与洞察",
          "文档理解与审核",
          "流程自动化",
          "智能助手与智能体应用",
        ],
      ],
      governance: "平台治理与权限控制贯穿能力建设和应用使用全过程",
      note: "正式视觉可替换为解决方案架构图、业务场景组合图或动画；本图仅解释关系，不承担跳转。",
    },
  },
  scenes: [
    {
      id: "overview-scene-knowledge",
      key: "knowledge-service",
      anchor: "scene-knowledge-service",
      category: "知识与数据智能",
      title: "企业知识问答与知识服务",
      problem: "企业知识分散，查找、理解和复用效率不足。",
      audience: "需要面向员工或业务人员提供统一知识服务的组织。",
      value: "让企业知识形成可检索、可问答、可持续维护的服务能力。",
      visual: "知识问答界面 / 知识检索过程 / 应用效果素材槽位",
      capabilities: ["知识底座", "智能体中心", "行业应用"],
    },
    {
      id: "overview-scene-data",
      key: "data-insight",
      anchor: "scene-data-insight",
      category: "知识与数据智能",
      title: "数据问答、分析与业务洞察",
      problem: "业务数据查询依赖专业人员，数据获取和分析链路较长。",
      audience: "需要通过自然语言查询业务数据并辅助分析的部门。",
      value: "降低业务数据使用门槛，缩短从问题到结果的路径。",
      visual: "自然语言问数 / SQL 查询转换 / 数据结果素材槽位",
      capabilities: ["数据源", "数据智能体", "应用服务"],
    },
    {
      id: "overview-scene-document",
      key: "document-intelligence",
      anchor: "scene-document-intelligence",
      category: "知识与数据智能",
      title: "文档理解、知识检索与智能审核",
      problem: "大量复杂文档需要人工阅读、检索、比对和审核。",
      audience: "对文档处理准确性、效率和可追溯性有要求的业务部门。",
      value: "提升文档信息提取、知识检索和辅助审核效率。",
      visual: "文档解析 / 内容提取 / 审核结果与流程素材槽位",
      capabilities: ["知识库", "知识加工", "流程编排"],
    },
    {
      id: "overview-scene-process",
      key: "process-automation",
      anchor: "scene-process-automation",
      category: "智能体与业务应用",
      title: "业务流程自动化与智能协同",
      problem: "重复业务流程依赖人工衔接，多环节协同效率有限。",
      audience: "希望将模型、知识、数据和工具组合成可执行流程的组织。",
      value: "通过可视化流程编排支撑多步骤任务自动执行与协同。",
      visual: "业务流程图 / Chatflow / Workflow 运行素材槽位",
      capabilities: ["流程编排", "模型能力", "知识与数据"],
    },
    {
      id: "overview-scene-assistant",
      key: "enterprise-assistant",
      anchor: "scene-enterprise-assistant",
      category: "智能体与业务应用",
      title: "企业内部智能助手",
      problem: "企业已有知识、数据和工具难以形成统一智能服务入口。",
      audience: "需要建设内部知识助手、业务助手或岗位助手的企业。",
      value: "将企业专有能力组合成面向员工和业务场景的可用应用。",
      visual: "智能助手应用界面 / 对话过程 / 服务入口素材槽位",
      capabilities: ["推理中心", "知识与数据", "应用广场"],
    },
    {
      id: "overview-scene-multi-agent",
      key: "multi-agent",
      anchor: "scene-multi-agent",
      category: "智能体与业务应用",
      title: "多智能体协同与复杂任务处理",
      problem: "单一智能体难以覆盖跨知识、数据、流程和工具的复杂任务。",
      audience: "需要多项智能能力协同完成复杂业务任务的场景。",
      value: "组合多个智能体能力，形成面向复杂任务的一体化应用服务。",
      visual: "单一智能体 → 联合智能体 → 业务结果素材槽位",
      capabilities: ["联合智能体", "流程编排", "应用服务"],
    },
  ],
  methods: [
    [
      "problem",
      "01 业务问题识别",
      "明确需要解决的业务问题、服务对象和建设边界。",
      "梳理业务流程、现有问题、使用角色及期望结果。",
      "业务问题清单、优先场景范围和初步建设目标。",
    ],
    [
      "assessment",
      "02 能力与数据评估",
      "确认现有算力环境、模型条件、知识数据基础和系统接口条件。",
      "评估数据可用性、知识质量、模型适配需求、部署环境和集成限制。",
      "能力与数据评估结果、风险清单和建设前提。",
    ],
    [
      "design",
      "03 方案设计",
      "形成覆盖业务、能力、数据、应用和交付边界的总体方案。",
      "设计总体架构、核心模块、业务流程、体验路径和实施范围。",
      "解决方案说明、总体架构图和场景建设清单。",
    ],
    [
      "combination",
      "04 产品能力组合",
      "选择能够支撑当前方案的华鲲产品模块与能力组合。",
      "匹配算力、模型、知识、数据、智能体、应用服务和平台治理能力。",
      "产品能力映射、模块组合关系和能力使用边界。",
    ],
    [
      "integration",
      "05 部署与系统集成",
      "将方案部署到目标环境并连接企业现有业务系统。",
      "完成环境部署、接口联调、权限配置、业务系统集成和场景验证。",
      "可运行环境、集成结果、验证记录和上线准备清单。",
    ],
    [
      "operation",
      "06 应用上线与持续优化",
      "让方案稳定服务实际业务，并根据使用效果持续优化。",
      "开展上线运营、效果观察、知识数据维护、智能体调优和场景扩展。",
      "运营反馈、优化方案、迭代记录和后续扩展计划。",
    ],
  ],
  industries: [
    [
      "government",
      "政务",
      "围绕政务知识、公文、业务数据与事项流程形成具体场景方案。",
      "当前预留 4 个可评审的行业场景入口。",
      "正式上线前需由业务侧确认场景和对外口径。",
      "政务行业场景全景图素材槽位",
      "查看政务场景 →",
    ],
    [
      "finance",
      "金融",
      "围绕制度产品知识、文档、经营数据与客户服务形成具体场景方案。",
      "当前预留 4 个可评审的行业场景入口。",
      "正式上线前需由业务侧确认场景和对外口径。",
      "金融行业场景全景图素材槽位",
      "查看金融场景 →",
    ],
    [
      "healthcare",
      "医疗",
      "围绕院内知识、文档信息、运营数据与行政流程形成辅助场景方案。",
      "当前预留 4 个可评审的行业场景入口。",
      "不涉及诊断或治疗，正式上线前确认对外口径。",
      "医疗行业场景全景图素材槽位",
      "查看医疗场景 →",
    ],
    [
      "enterprise",
      "企业智能化",
      "围绕企业知识、经营数据、文档、流程和多智能体形成场景方案。",
      "当前预留 5 个可评审的行业场景入口。",
      "正式上线前需由业务侧确认场景和对外口径。",
      "企业智能化场景全景图素材槽位",
      "查看企业场景 →",
    ],
  ],
  industryNote:
    "行业名称仅用于低保真目录与模板评审，不代表已经获得首期对外发布确认；未确认行业在正式官网不展示可点击空页面。",
  support: [
    ["模型与运行支撑", "模型管理、训练、评估、部署和调用", "/product/model"],
    ["模型能力", "模型管理、训练、评估、部署和调用", "/product/model"],
    ["知识增强", "知识库、数据源和企业知识数据利用", "/product/knowledge"],
    ["智能体开发", "推理中心、流程编排、调试与发布", "/product/agents"],
    [
      "应用广场与服务",
      "应用承接、组合、行业推广和外部调用",
      "/product/applications",
    ],
  ],
  governance: [
    "平台治理横向贯穿",
    "用户、角色和菜单管理支撑各能力模块的有序使用",
    "查看安全中心 →",
    "/product/governance",
  ],
  case: {
    title: "案例内容待授权补充",
    label: "首期案例接口预留",
    visual: "客户 Logo / 项目图片 / 应用成果素材槽位\n待获得公开授权后补充",
    fields: [
      ["所属行业：", "待获得公开授权后补充"],
      ["业务问题：", "待获得公开授权后补充"],
      ["使用能力：", "待获得公开授权后补充"],
      ["成果摘要：", "待获得公开授权后补充，不使用虚构比例或数据"],
    ],
    link: [
      "查看案例详情模板 →",
      "/solutions/case-pending-enterprise-knowledge#case-pending-enterprise-knowledge",
    ],
  },
  cta: {
    title: "希望围绕实际业务问题规划 AI 解决方案？",
    description:
      "面向场景梳理、方案设计、能力组合、私有化部署和系统集成需求，与华鲲团队进一步沟通。",
    actions: [
      ["商务咨询", "/contact?topic=解决方案咨询"],
      ["申请体验", "/trial"],
    ],
    note: "商务咨询自动带入“解决方案咨询”；从具体方案或行业进入时，后续表单继续带入方案名称与行业来源。申请体验范围以实际开放能力为准。",
  },
} as const;
