import type {
  CommonSolutionDetail,
  SolutionProduct,
} from "./solution-detail-content";

type ProductKey =
  | "model"
  | "knowledge"
  | "agents"
  | "applications"
  | "governance";

const productMeta: Record<ProductKey, Omit<SolutionProduct, "href">> = {
  model: {
    name: "模型中心",
    role: "提供模型纳管、训练、评估、部署与任务调度能力。",
  },
  knowledge: {
    name: "企业知识库",
    role: "提供文档接入、分片、图谱与知识问答的知识底座。",
  },
  agents: {
    name: "智能体中心",
    role: "提供知识、数据、视频与流程编排四类智能体能力。",
  },
  applications: {
    name: "行业应用中心",
    role: "提供面向行业场景成熟可用的智能应用。",
  },
  governance: {
    name: "安全中心",
    role: "提供用户、角色、菜单与数据权限治理。",
  },
};

const productHref: Record<ProductKey, string> = {
  model: "/product/model",
  knowledge: "/product/knowledge",
  agents: "/product/agents",
  applications: "/product/applications",
  governance: "/product/governance",
};

const refinedProductHrefs: Record<
  string,
  Partial<Record<ProductKey, string>>
> = {
  "private-yuanqi": { model: "/product/model-deploy" },
  "cluster-planning": { model: "/product/model-task-center" },
  "compute-monitoring": { model: "/product/model-task-center" },
  "model-evaluation": { model: "/product/model-evaluation" },
  "model-deployment": { model: "/product/model-deploy" },
  "knowledge-service": { agents: "/product/agent-knowledge" },
  "document-intelligence": {
    agents: "/product/agent-knowledge",
    applications: "/product/app-contract",
  },
  "data-insight": {
    knowledge: "/product/knowledge-metrics",
    agents: "/product/data-agent",
  },
  "unstructured-data": { agents: "/product/data-agent" },
  "knowledge-assets": { agents: "/product/agent-knowledge" },
  "process-automation": { agents: "/product/agent-orchestration" },
  "video-intelligence": { agents: "/product/agent-video" },
  "enterprise-assistant": { agents: "/product/agent-knowledge" },
};

function products(
  slug: string,
  keys: readonly ProductKey[],
): SolutionProduct[] {
  return keys.map((key) => ({
    ...productMeta[key],
    href: refinedProductHrefs[slug]?.[key] ?? productHref[key],
  }));
}

export const commonSolutionDetails = {
  "private-yuanqi": {
    kind: "common",
    category: "基础设施与模型工程",
    title: "元启私有化部署方案",
    summary:
      "面向企业目标环境完成元启平台、基础资源、访问治理与业务系统衔接的整体部署。",
    audience: "需要内网部署、数据不出域或自主运行企业 AI 平台的组织。",
    tags: ["环境自主可控", "数据不出域", "平台自主运行", "业务系统衔接"],
    scenarios: ["企业内网 AI 平台建设", "现有业务系统中的元启能力接入"],
    problems: [
      "目标环境、网络和资源条件需要统一评估",
      "平台模块部署范围与访问边界需要明确",
      "上线后的运行保障与扩展方式需要规划",
    ],
    components: [
      "部署环境与资源评估",
      "元启平台模块部署",
      "用户角色与访问配置",
      "业务系统及接口联调",
    ],
    flow: [
      "环境调研",
      "部署方案确认",
      "资源和网络准备",
      "平台部署",
      "能力验证",
      "上线交付",
    ],
    related: ["cluster-planning"],
    products: products("private-yuanqi", [
      "model",
      "knowledge",
      "agents",
      "applications",
      "governance",
    ]),
  },
  "cluster-planning": {
    kind: "common",
    category: "基础设施与模型工程",
    title: "单机与集群算力规划方案",
    summary: "根据模型任务和业务规模规划单机或集群资源组织与运行方式。",
    audience: "需要确定算力规模、节点组织和模型任务资源配置的组织。",
    tags: ["单机集群匹配", "任务资源规划", "资源统一管理", "扩容路径清晰"],
    scenarios: ["单机模型验证与起步建设", "多节点集群与多任务运行规划"],
    problems: [
      "单机与集群选择缺少业务和任务依据",
      "不同模型任务的资源需求需要匹配",
      "后续扩容与统一管理方式需要预留",
    ],
    components: [
      "业务与任务规模评估",
      "单机资源规划",
      "集群节点与资源组织",
      "扩容和调度边界设计",
    ],
    flow: [
      "任务梳理",
      "资源测算",
      "架构选择",
      "节点规划",
      "任务验证",
      "扩展建议",
    ],
    related: ["compute-monitoring"],
    products: products("cluster-planning", ["model"]),
  },
  "compute-monitoring": {
    kind: "common",
    category: "基础设施与模型工程",
    title: "算力监控与运行保障方案",
    summary:
      "对 CPU、内存、磁盘、网络和 AI 卡等资源状态进行统一观察和运行保障。",
    audience: "需要掌握算力使用状态、性能趋势和异常排查依据的运维与平台团队。",
    tags: ["资源状态可视", "多指标监控", "运行趋势掌握", "异常排查支撑"],
    scenarios: ["日常算力运行监控", "模型任务异常辅助排查"],
    problems: [
      "资源运行状态缺少统一视图",
      "性能变化与模型任务之间难以关联",
      "异常发生后缺少排查信息和运行趋势依据",
    ],
    components: [
      "资源监控概览",
      "关键指标观察",
      "运行趋势分析",
      "异常排查与保障支持",
    ],
    flow: [
      "监控接入",
      "指标采集",
      "状态观察",
      "趋势识别",
      "异常定位",
      "运行优化",
    ],
    related: ["cluster-planning", "model-deployment"],
    products: products("compute-monitoring", ["model"]),
  },
  "model-evaluation": {
    kind: "common",
    category: "基础设施与模型工程",
    title: "模型适配、训练与效果验证",
    summary: "围绕实际业务任务完成模型选择、数据准备、训练评估和持续优化。",
    audience: "需要验证模型是否适配业务并形成上线决策依据的算法与业务团队。",
    tags: ["模型业务适配", "训练评估闭环", "效果对比验证", "优化决策有据"],
    scenarios: [
      "业务模型选择与基线评估",
      "企业数据驱动的模型训练或微调",
      "训练前后效果对比与上线判断",
    ],
    problems: [
      "可选模型较多但缺少统一比较依据",
      "训练和评估数据需要规范准备",
      "模型效果与业务目标之间需要持续验证",
    ],
    components: [
      "模型与任务选择",
      "训练评估数据准备",
      "模型训练与优化",
      "模型评估与结果对比",
      "部署决策与版本沉淀",
    ],
    flow: [
      "任务定义",
      "模型选择",
      "数据准备",
      "训练执行",
      "效果评估",
      "优化与部署决策",
    ],
    related: ["model-deployment", "knowledge-assets"],
    products: products("model-evaluation", ["model"]),
  },
  "model-deployment": {
    kind: "common",
    category: "基础设施与模型工程",
    title: "企业模型部署与调用",
    summary: "将已准备、训练或评估的模型部署为可管理、可调用的企业模型服务。",
    audience: "需要为智能体、应用或现有系统提供稳定模型调用能力的组织。",
    tags: ["模型统一部署", "推理服务可用", "调用接口衔接", "智能体能力支撑"],
    scenarios: [
      "企业大模型服务部署",
      "智能体底层模型调用",
      "已有业务系统模型 API 接入",
    ],
    problems: [
      "模型文件和运行环境需要统一管理",
      "推理服务的资源和可用状态需要保障",
      "调用入口与后续应用集成方式需要明确",
    ],
    components: [
      "模型来源与版本管理",
      "部署环境和资源准备",
      "模型服务部署",
      "推理调用验证",
      "接口与应用衔接",
    ],
    flow: [
      "模型确认",
      "环境准备",
      "服务部署",
      "调用测试",
      "智能体接入",
      "运行维护",
    ],
    related: ["model-evaluation", "enterprise-assistant"],
    products: products("model-deployment", ["model", "agents", "applications"]),
  },
  "knowledge-service": {
    kind: "common",
    category: "知识与数据智能",
    title: "企业知识问答与知识服务",
    summary:
      "将企业文档、制度、产品资料和专业知识转化为可检索、可问答的智能知识服务。",
    audience: "需要建设员工知识助手、客户服务知识入口或专业知识服务的组织。",
    tags: ["企业知识可问", "检索回答准确", "知识持续维护", "多入口知识服务"],
    scenarios: [
      "内部制度与管理知识问答",
      "产品资料与售前知识服务",
      "技术文档与运维知识检索",
      "客服与业务咨询辅助",
      "岗位知识助手",
    ],
    problems: [
      "知识分散且更新频繁，查找路径长",
      "传统关键词检索难以理解自然语言问题",
      "回答质量、知识来源和持续维护缺少闭环",
    ],
    components: [
      "企业知识接入",
      "文档解析与智能分片",
      "知识库构建与质量优化",
      "知识智能体配置与调试",
      "应用发布与业务使用",
      "权限与访问控制",
    ],
    flow: [
      "企业资料接入",
      "知识处理",
      "智能体构建",
      "用户提问",
      "知识检索与模型生成",
      "返回结果",
      "持续标注和优化",
    ],
    related: [
      "document-intelligence",
      "knowledge-assets",
      "enterprise-assistant",
    ],
    products: products("knowledge-service", [
      "knowledge",
      "agents",
      "applications",
      "governance",
    ]),
  },
  "document-intelligence": {
    kind: "common",
    category: "知识与数据智能",
    title: "文档理解、知识检索与智能审核",
    summary:
      "组合文档解析、知识检索、智能体和流程能力，辅助完成复杂文档处理与审核。",
    audience: "合同、报告、制度、申报材料或专业文档处理量较大的业务部门。",
    tags: ["文档自动解析", "关键信息提取", "知识快速检索", "审核流程提效"],
    scenarios: [
      "复杂文档内容提取",
      "文档知识检索与定位",
      "多文档信息比对",
      "规则辅助审核",
      "审核结果整理与流转",
    ],
    problems: [
      "文档格式多样且信息分布复杂",
      "人工检索和比对耗时且容易遗漏",
      "审核规则、知识依据和处理流程难以统一",
    ],
    components: [
      "文档接入与解析",
      "内容分片和结构化提取",
      "知识检索与信息定位",
      "审核规则与流程编排",
      "结果生成与人工复核",
    ],
    flow: [
      "文档提交",
      "解析与提取",
      "知识或规则匹配",
      "内容检索与比对",
      "审核结果生成",
      "人工复核",
      "结果归档",
    ],
    related: ["knowledge-service", "unstructured-data", "process-automation"],
    products: products("document-intelligence", [
      "knowledge",
      "agents",
      "applications",
    ]),
  },
  "data-insight": {
    kind: "common",
    category: "知识与数据智能",
    title: "数据问答、分析与业务洞察",
    summary:
      "连接企业业务数据，通过自然语言问题生成查询并返回可理解的数据结果与分析线索。",
    audience: "希望降低数据查询门槛、提高业务分析效率的管理与业务部门。",
    tags: ["自然语言问数", "数据查询降门槛", "分析结果直达", "业务决策辅助"],
    scenarios: [
      "经营数据自然语言查询",
      "业务指标快速获取",
      "多表数据关联分析",
      "异常数据辅助发现",
      "管理决策数据支持",
    ],
    problems: [
      "数据分散在数据库、表格或业务系统中",
      "业务人员依赖技术人员编写查询",
      "查询结果与业务理解之间仍需人工转换",
    ],
    components: [
      "企业直连或表多多接入",
      "数据结构与业务口径配置",
      "自然语言问题理解",
      "SQL 等查询生成与执行",
      "结果展示与分析反馈",
    ],
    flow: [
      "数据源接入",
      "表结构与口径确认",
      "用户自然语言提问",
      "查询语句生成",
      "数据检索",
      "结果返回",
      "反馈与优化",
    ],
    related: [
      "unstructured-data",
      "enterprise-assistant",
      "process-automation",
    ],
    products: products("data-insight", ["knowledge", "agents", "applications"]),
  },
  "knowledge-assets": {
    kind: "common",
    category: "知识与数据智能",
    title: "企业知识库建设与持续运营",
    summary:
      "围绕文档、分片、QA、术语、知识图谱和质量测试形成持续运营的企业知识资产。",
    audience: "需要长期建设和维护企业知识体系、知识标准与复用机制的组织。",
    tags: ["知识统一沉淀", "分片 QA 维护", "质量持续优化", "知识跨库复用"],
    scenarios: [
      "企业知识库统一建设",
      "文档分片与知识整理",
      "QA 与业务术语沉淀",
      "知识质量测试与优化",
      "跨知识库知识复用",
    ],
    problems: [
      "知识资料缺少统一归集和维护机制",
      "分片、QA 与术语质量直接影响检索效果",
      "知识更新、复用和质量验证缺少持续流程",
    ],
    components: [
      "知识资料接入",
      "智能分片与标注",
      "QA 和术语构建",
      "搜索测试与质量优化",
      "知识图谱关联",
      "知识权限与维护",
    ],
    flow: [
      "资料归集",
      "文档解析与分片",
      "标注及QA补充",
      "检索测试",
      "质量优化",
      "发布使用",
      "持续维护",
    ],
    related: [
      "knowledge-service",
      "document-intelligence",
      "unstructured-data",
    ],
    products: products("knowledge-assets", [
      "knowledge",
      "agents",
      "governance",
    ]),
  },
  "unstructured-data": {
    kind: "common",
    category: "知识与数据智能",
    title: "非结构化数据处理与业务利用",
    summary:
      "将文档等非结构化内容解析为结构化数据，衔接查询、分析、数据问答和业务流程。",
    audience: "拥有大量文档资料但需要按字段管理、查询和分析的组织。",
    tags: ["多格式内容接入", "内容结构化处理", "统一数据管理", "数据业务复用"],
    scenarios: [
      "业务文档字段提取",
      "历史资料结构化整理",
      "多格式内容统一入库",
      "结构化结果查询分析",
      "数据问答与业务流程调用",
    ],
    problems: [
      "非结构化资料无法直接参与表格和数据库查询",
      "人工录入结构化字段效率低且标准不统一",
      "处理结果需要继续进入数据管理和业务使用",
    ],
    components: [
      "非结构化资料接入",
      "文档解析与字段识别",
      "数据清洗与结构化转换",
      "结构化存储与管理",
      "查询分析与应用调用",
    ],
    flow: [
      "资料上传或接入",
      "内容解析",
      "字段提取",
      "结构化校验",
      "数据存储",
      "查询与分析",
      "业务应用调用",
    ],
    related: ["data-insight", "document-intelligence", "knowledge-assets"],
    products: products("unstructured-data", [
      "knowledge",
      "agents",
      "applications",
    ]),
  },
  "process-automation": {
    kind: "common",
    category: "智能体与业务应用",
    title: "业务流程自动化与智能协同",
    summary:
      "通过可视化流程将模型、知识、数据、工具和业务逻辑组合为可执行的智能工作流。",
    audience: "希望减少重复操作、连接多项能力并实现跨步骤协同的组织。",
    tags: ["流程可视编排", "多能力组合", "任务自动执行", "流程持续优化"],
    scenarios: [
      "多步骤业务任务自动执行",
      "文档处理与审批辅助",
      "知识与数据联合处理",
      "跨系统信息流转",
      "Chatflow 多轮业务协同",
    ],
    problems: [
      "多步骤任务依赖人工在系统间反复操作",
      "模型、知识、数据和工具能力彼此割裂",
      "流程调整、调试和运行效果缺少统一管理",
    ],
    components: [
      "业务流程梳理",
      "标准或 AI 创建流程",
      "Chatflow 与 Workflow 设计",
      "节点和工具配置",
      "流程调试与验证",
      "发布与外部调用",
    ],
    flow: [
      "业务任务输入",
      "问题分类与流程路由",
      "模型/知识/数据节点执行",
      "工具或系统调用",
      "结果汇总",
      "人工确认",
      "发布与持续优化",
    ],
    related: ["document-intelligence", "enterprise-assistant", "multi-agent"],
    products: products("process-automation", [
      "model",
      "knowledge",
      "agents",
      "applications",
    ]),
  },
  "enterprise-assistant": {
    kind: "common",
    category: "智能体与业务应用",
    title: "企业内部智能助手",
    summary:
      "组合企业知识、业务数据、模型和工具，为员工或岗位提供统一智能服务入口。",
    audience: "计划建设员工助手、岗位助手、管理助手或内部业务服务入口的企业。",
    tags: ["统一智能入口", "知识数据协同", "岗位工作辅助", "权限可控使用"],
    scenarios: [
      "员工制度与知识助手",
      "销售与售前业务助手",
      "运营数据查询助手",
      "技术支持与运维助手",
      "管理决策信息助手",
    ],
    problems: [
      "员工需要在多个系统和资料中查找信息",
      "不同岗位使用的知识、数据和工具相互分散",
      "通用助手缺少企业专有知识和业务能力",
    ],
    components: [
      "助手场景与角色设计",
      "模型和提示词配置",
      "知识库与数据源关联",
      "工具及流程接入",
      "在线调试和标注优化",
      "应用发布与权限控制",
    ],
    flow: [
      "用户进入助手",
      "问题与意图识别",
      "知识/数据/工具调用",
      "模型生成与业务处理",
      "结果返回",
      "反馈标注",
      "持续优化",
    ],
    related: ["knowledge-service", "data-insight", "process-automation"],
    products: products("enterprise-assistant", [
      "knowledge",
      "agents",
      "applications",
      "governance",
    ]),
  },
  "multi-agent": {
    kind: "common",
    category: "智能体与业务应用",
    title: "多智能体协同与复杂任务处理",
    summary:
      "组合多个专业智能体及流程能力，协同完成单一智能体难以覆盖的复杂任务。",
    audience: "需要跨知识、数据、工具或业务角色完成复杂任务的组织。",
    tags: ["多智能体协同", "复杂任务拆解", "能力统一编排", "结果一体交付"],
    scenarios: [
      "复杂问题分工处理",
      "知识与数据联合分析",
      "多角色业务协同",
      "跨流程任务编排",
      "综合业务结果生成",
    ],
    problems: [
      "复杂任务包含多个专业步骤和不同能力要求",
      "单一智能体上下文、工具和职责范围有限",
      "多项结果需要统一协调、汇总和验证",
    ],
    components: [
      "复杂任务拆解",
      "专业智能体设计",
      "协同关系与路由",
      "知识数据和工具挂接",
      "联合调试与结果汇总",
      "应用发布与运行管理",
    ],
    flow: [
      "复杂任务输入",
      "任务识别与拆分",
      "智能体选择与分发",
      "各智能体执行",
      "结果协调与校验",
      "统一结果生成",
      "反馈与优化",
    ],
    related: ["process-automation", "enterprise-assistant", "data-insight"],
    products: products("multi-agent", [
      "model",
      "knowledge",
      "agents",
      "applications",
    ]),
  },
  "video-intelligence": {
    kind: "common",
    category: "智能体与业务应用",
    title: "视频内容检索与智能分析",
    summary:
      "围绕视频内容建立可检索、可定位、可问答和可衔接业务应用的智能分析能力。",
    audience: "拥有大量视频资料并需要快速查找目标内容或开展辅助分析的组织。",
    tags: ["视频内容检索", "目标快速定位", "视频智能分析", "结果业务复用"],
    scenarios: [
      "视频内容快速检索",
      "目标片段定位",
      "视频事件辅助分析",
      "视频资料知识化利用",
    ],
    problems: [
      "视频内容需要逐段人工查看",
      "目标信息难以通过文本条件快速定位",
      "视频分析结果难以衔接知识与业务流程",
    ],
    components: [
      "视频资源接入",
      "视频内容理解与索引",
      "视频智能体配置",
      "检索与定位交互",
      "结果展示与业务衔接",
    ],
    flow: [
      "视频接入",
      "内容处理",
      "索引构建",
      "用户检索",
      "目标片段定位",
      "结果分析",
      "应用调用",
    ],
    related: ["enterprise-assistant", "multi-agent"],
    products: products("video-intelligence", [
      "model",
      "agents",
      "applications",
    ]),
  },
} satisfies Record<string, CommonSolutionDetail>;
