export const prototypePageRoutes = {
  home: "/",
  products: "/product",
  "key-products": "/product/standalone",
  "mdd-2": "/product/code-agent",
  aippt: "/product/aippt",
  aishrek: "/product/aishrek",
  "model-optimization": "/product/model-optimization",
  "model-task-center": "/product/model-task-center",
  model: "/product/model",
  "model-assets": "/product/model-assets",
  "model-training": "/product/model-training",
  "model-evaluation": "/product/model-evaluation",
  "agent-knowledge-base": "/product/agent-knowledge-base",
  knowledge: "/product/knowledge",
  "knowledge-metrics": "/product/knowledge-metrics",
  "model-data": "/product/model-data",
  "model-deploy": "/product/model-deploy",
  coding: "/product/coding",
  "coding-project": "/product/coding-project",
  "coding-session": "/product/coding-session",
  "coding-mobile": "/product/coding-mobile",
  "coding-standard": "/product/coding-standard",
  agents: "/product/agents",
  "agent-knowledge": "/product/agent-knowledge",
  "agent-data": "/product/data-agent",
  "agent-video": "/product/agent-video",
  "agent-orchestration": "/product/agent-orchestration",
  applications: "/product/applications",
  "app-writing": "/product/app-writing",
  "app-bidding": "/product/app-bidding",
  "app-contract": "/product/app-contract",
  skills: "/product/skills",
  "skills-programming": "/product/skills-programming",
  "skills-application": "/product/skills-application",
  "skills-office": "/product/skills-office",
  governance: "/product/governance",
  solutions: "/solutions/finance-compliance",
  "solution-detail": "/solutions/[slug]",
  downloads: "/downloads",
  partners: "/partners",
  pricing: "/pricing",
  contact: "/contact",
  trial: "/trial",
} as const;

export const partnerKeys = [
  "overview",
  "business",
  "business-modes",
  "business-tiers",
  "business-benefits",
  "policy",
  "policy-types",
  "policy-cert",
  "policy-resources",
  "training",
  "training-system",
  "training-courses",
  "training-path",
  "training-resources",
  "become",
] as const;

export const downloadResourceKeys = [
  "yuanqi-fullstack",
  "yuanqi-appliance",
  "yuanqi-cases",
  "yuanqi-folder",
  "yuanqi-usage",
  "mdd2-intro",
  "mdd2-solution",
  "office-appliance",
  "office-doc",
  "office-contract",
  "office-bid",
  "daoban-appliance",
  "daoban-gov",
  "daoban-assistant",
  "vision-folder",
  "vision-solution",
  "vision-intro",
  "vision-usage",
  "mdd2-client",
  "yuanqi-deploy",
  "yuanqi-faq",
  "wp-yuanqi-tech",
] as const;
