import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { compileSafeDocument } from "./markdown";
import {
  computeLegacyFixtureChecksum,
  convertLegacyMdx,
  LEGACY_FIXTURE_CHECKSUMS,
  parseLegacyMeta,
} from "./legacy-mdx";

export const DOCUMENT_SEED_MANIFEST = [
  {
    id: "019f79c8-9a00-7000-8000-000000000001",
    revisionId: "019f79c8-9a00-7000-9000-000000000001",
    slug: "quick-start",
    label: "快速开始",
    code: "QUICK_START",
    position: 10,
    bodyChecksum:
      "33ddd1cd30f25884725d4cdf0bd0aef0ff85742d0dc382a7e47495b2edf64838",
  },
  {
    id: "019f79c8-9a00-7000-8000-000000000002",
    revisionId: "019f79c8-9a00-7000-9000-000000000002",
    slug: "deployment",
    label: "部署指南",
    code: "DEPLOYMENT",
    position: 20,
    bodyChecksum:
      "08488fdcd68d1c3ba072b4cddf193185c12cd4d19e81255a6a0465efffcb9ec9",
  },
  {
    id: "019f79c8-9a00-7000-8000-000000000003",
    revisionId: "019f79c8-9a00-7000-9000-000000000003",
    slug: "upgrade",
    label: "升级手册",
    code: "UPGRADE",
    position: 30,
    bodyChecksum:
      "f77bdd3eee2ed93f82d5c3a8f84b16f730aa60fa1f23b5525eb0db55bf5c71f9",
  },
  {
    id: "019f79c8-9a00-7000-8000-000000000004",
    revisionId: "019f79c8-9a00-7000-9000-000000000004",
    slug: "operations",
    label: "运维手册",
    code: "OPERATIONS",
    position: 40,
    bodyChecksum:
      "4142998b2dad762895a6913d69bf4b86f53a5761ab832b18846d6570ad9e5053",
  },
  {
    id: "019f79c8-9a00-7000-8000-000000000005",
    revisionId: "019f79c8-9a00-7000-9000-000000000005",
    slug: "api",
    label: "API 文档",
    code: "API",
    position: 50,
    bodyChecksum:
      "544aacad1561d60ebd9e1d87c8f89555139c436f19f7ae0a57cb99822ca64e8d",
  },
  {
    id: "019f79c8-9a00-7000-8000-000000000006",
    revisionId: "019f79c8-9a00-7000-9000-000000000006",
    slug: "hardware",
    label: "GPU / 硬件适配",
    code: "HARDWARE",
    position: 60,
    bodyChecksum:
      "5acbf90b4eea4cfcb78f0a52e4bfd362da32ec96e88c4ab989cdb86f701893c4",
  },
  {
    id: "019f79c8-9a00-7000-8000-000000000007",
    revisionId: "019f79c8-9a00-7000-9000-000000000007",
    slug: "faq",
    label: "常见问题 FAQ",
    code: "FAQ",
    position: 70,
    bodyChecksum:
      "c52d93faddff6e97e7c95b14bba6fce65fc3900289818c6e2cf767ff017a4006",
  },
] as const;

const fixtureDirectory = fileURLToPath(
  new URL("../fixtures/legacy/", import.meta.url),
);
const defaultMigration = fileURLToPath(
  new URL("../../database/drizzle/0007_cms_document_seed.sql", import.meta.url),
);
const seededAt = "2026-07-19T00:00:00.000Z";

export type DocumentSeed = ReturnType<typeof buildDocumentSeeds>[number];

export function buildDocumentSeeds() {
  const metaSource = readFixture("_meta.ts");
  const meta = new Map(parseLegacyMeta(metaSource));
  if (meta.size !== DOCUMENT_SEED_MANIFEST.length) {
    throw new Error("DOCUMENT_SEED_META_MISMATCH");
  }

  return DOCUMENT_SEED_MANIFEST.map((entry) => {
    if (meta.get(entry.slug) !== entry.label) {
      throw new Error(`DOCUMENT_SEED_META_MISMATCH:${entry.slug}`);
    }
    const converted = convertLegacyMdx(readFixture(`${entry.slug}.mdx`));
    if (converted.title !== entry.label) {
      throw new Error(`DOCUMENT_SEED_TITLE_MISMATCH:${entry.slug}`);
    }
    const body = compileSafeDocument({
      slug: entry.slug,
      title: converted.title,
      summary: converted.summary,
      source: converted.source,
      navigation: {
        label: entry.label,
        code: entry.code,
        position: entry.position,
      },
    });
    if (body.checksum !== entry.bodyChecksum) {
      throw new Error(`DOCUMENT_SEED_BODY_DRIFT:${entry.slug}`);
    }
    return { ...entry, ...converted, body };
  });
}

export function generateDocumentSeedSql(): string {
  const seeds = buildDocumentSeeds();
  const chunks = seeds.map(renderSeedChunk);
  return [
    "-- Generated by @ai-agent-platform/document-content. Do not edit by hand.",
    "-- Regenerate with: pnpm --filter @ai-agent-platform/document-content seed:generate",
    "-- Must run in one Drizzle migration transaction; partial seed prefixes are rejected, not resumed.",
    renderPartialSeedGuard(seeds),
    ...chunks,
    "",
  ].join("\n");
}

export function verifyGeneratedSeed(target = defaultMigration): void {
  const directory = mkdtempSync(join(tmpdir(), "cms-document-seed-check-"));
  const generated = join(directory, "0007_cms_document_seed.sql");
  try {
    writeFileSync(generated, generateDocumentSeedSql());
    const expected = readFileSync(generated);
    const actual = readFileSync(target);
    if (!expected.equals(actual)) {
      throw new Error(`DOCUMENT_SEED_OUT_OF_DATE:${target}`);
    }
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}

function readFixture(name: keyof typeof LEGACY_FIXTURE_CHECKSUMS): string {
  const source = readFileSync(join(fixtureDirectory, name), "utf8");
  if (computeLegacyFixtureChecksum(source) !== LEGACY_FIXTURE_CHECKSUMS[name]) {
    throw new Error(`DOCUMENT_SEED_FIXTURE_DRIFT:${name}`);
  }
  return source;
}

function renderPartialSeedGuard(seeds: readonly DocumentSeed[]): string {
  const identities = seeds
    .map(
      ({ id, revisionId, slug }) =>
        `    (${quoteSql(id)}::uuid, ${quoteSql(revisionId)}::uuid, ${quoteSql(slug)})`,
    )
    .join(",\n");
  return `DO $$
DECLARE
  exact_content_count integer;
  exact_revision_count integer;
  exact_route_count integer;
BEGIN
  SELECT count(*) INTO exact_content_count
  FROM "content" c
  JOIN (VALUES
${identities}
  ) AS expected("content_id", "revision_id", "slug")
    ON c."id" = expected."content_id" AND c."slug" = expected."slug";

  SELECT count(*) INTO exact_revision_count
  FROM "content_revisions" cr
  JOIN (VALUES
${identities}
  ) AS expected("content_id", "revision_id", "slug")
    ON cr."id" = expected."revision_id"
      AND cr."content_id" = expected."content_id"
      AND cr."revision" = 1;

  SELECT count(*) INTO exact_route_count
  FROM "content_routes" r
  JOIN (VALUES
${identities}
  ) AS expected("content_id", "revision_id", "slug")
    ON r."slug" = expected."slug" AND r."content_id" = expected."content_id";

  IF exact_content_count NOT IN (0, ${seeds.length})
    OR exact_revision_count <> exact_content_count
    OR exact_route_count <> exact_content_count THEN
    RAISE EXCEPTION 'DOCUMENT_SEED_PARTIAL_STATE' USING ERRCODE = '23514';
  END IF;
END;
$$;--> statement-breakpoint`;
}

function renderSeedChunk(seed: DocumentSeed): string {
  const body = quoteSqlJson(seed.body);
  const slug = quoteSql(seed.slug);
  const title = quoteSql(seed.title);
  const summary = quoteSql(seed.summary);
  const id = quoteSql(seed.id);
  const revisionId = quoteSql(seed.revisionId);

  return `-- Document seed: ${seed.slug}
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM "content"
    WHERE ("id" = ${id}::uuid OR "slug" = ${slug})
      AND NOT ("id" = ${id}::uuid AND "slug" = ${slug})
  ) OR EXISTS (
    SELECT 1 FROM "content"
    WHERE "id" = ${id}::uuid AND "slug" = ${slug}
      AND ("type" IS DISTINCT FROM 'document'
        OR "title" IS DISTINCT FROM ${title}
        OR "summary" IS DISTINCT FROM ${summary}
        OR "body" IS DISTINCT FROM ${body}::jsonb
        OR "status" IS DISTINCT FROM 'published'::"content_status"
        OR "revision" IS DISTINCT FROM 1
        OR "row_version" IS DISTINCT FROM 1
        OR "published_revision" IS DISTINCT FROM 1
        OR "archived_at" IS NOT NULL
        OR "deleted_at" IS NOT NULL)
  ) OR EXISTS (
    SELECT 1 FROM "content_revisions"
    WHERE ("id" = ${revisionId}::uuid OR ("content_id" = ${id}::uuid AND "revision" = 1))
      AND ("id" IS DISTINCT FROM ${revisionId}::uuid
        OR "content_id" IS DISTINCT FROM ${id}::uuid
        OR "revision" IS DISTINCT FROM 1
        OR "slug" IS DISTINCT FROM ${slug}
        OR "title" IS DISTINCT FROM ${title}
        OR "summary" IS DISTINCT FROM ${summary}
        OR "body" IS DISTINCT FROM ${body}::jsonb
        OR "created_by" IS NOT NULL
        OR "created_at" IS DISTINCT FROM '${seededAt}'::timestamptz)
  ) OR EXISTS (
    SELECT 1 FROM "content_routes"
    WHERE "slug" = ${slug}
      AND ("content_id" IS DISTINCT FROM ${id}::uuid OR "state" = 'alias')
  ) THEN
    RAISE EXCEPTION 'DOCUMENT_SEED_IDENTITY_COLLISION:${seed.slug}' USING ERRCODE = '23505';
  END IF;
END;
$$;--> statement-breakpoint
INSERT INTO "content" (
  "id", "type", "slug", "title", "summary", "body", "status",
  "published_at", "created_at", "updated_at", "revision", "row_version", "published_revision"
) VALUES (
  ${id}::uuid, 'document', ${slug}, ${title}, ${summary}, ${body}::jsonb, 'published',
  '${seededAt}'::timestamptz, '${seededAt}'::timestamptz, '${seededAt}'::timestamptz, 1, 1, NULL
) ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "content_revisions" (
  "id", "content_id", "revision", "slug", "title", "summary", "body", "created_at"
) VALUES (
  ${revisionId}::uuid, ${id}::uuid, 1, ${slug}, ${title}, ${summary}, ${body}::jsonb, '${seededAt}'::timestamptz
) ON CONFLICT DO NOTHING;--> statement-breakpoint
UPDATE "content"
SET "published_revision" = 1
WHERE "id" = ${id}::uuid AND "published_revision" IS NULL;--> statement-breakpoint
INSERT INTO "content_routes" ("slug", "content_id", "state", "created_at")
VALUES (${slug}, ${id}::uuid, 'reserved', '${seededAt}'::timestamptz)
ON CONFLICT DO NOTHING;--> statement-breakpoint
UPDATE "content_routes"
SET "state" = 'canonical'
WHERE "slug" = ${slug} AND "content_id" = ${id}::uuid AND "state" = 'reserved';--> statement-breakpoint`;
}

function quoteSql(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function quoteSqlJson(value: unknown): string {
  return quoteSql(JSON.stringify(value));
}

function runCli(): void {
  const command = process.argv[2];
  const target = resolve(process.argv[3] ?? defaultMigration);
  if (command === "generate") {
    writeFileSync(target, generateDocumentSeedSql());
    return;
  }
  if (command === "check") {
    verifyGeneratedSeed(target);
    return;
  }
  throw new Error("Usage: seed.ts <generate|check> [target]");
}

const entrypoint = process.argv[1]
  ? pathToFileURL(resolve(process.argv[1])).href
  : undefined;
if (entrypoint === import.meta.url) {
  try {
    runCli();
  } catch (error) {
    process.stderr.write(`${error instanceof Error ? error.message : error}\n`);
    process.exitCode = 1;
  }
}
