import {
  accounts,
  rateLimits,
  sessions,
  twoFactors,
  users,
  verifications,
} from "./schema/identity";

export const betterAuthModels = {
  user: {
    exportName: "users",
    tableName: "users",
    table: users,
    fields: {
      id: "id",
      name: "name",
      email: "email",
      emailVerified: "emailVerified",
      image: "image",
      createdAt: "createdAt",
      updatedAt: "updatedAt",
      twoFactorEnabled: "twoFactorEnabled",
      identityRealm: "identityRealm",
      status: "status",
      emailVerificationStatus: "emailVerificationStatus",
      username: "username",
      displayUsername: "displayUsername",
      mustChangePassword: "mustChangePassword",
      lastLoginAt: "lastLoginAt",
    },
  },
  session: {
    exportName: "sessions",
    tableName: "sessions",
    table: sessions,
    fields: {
      id: "id",
      expiresAt: "expiresAt",
      token: "token",
      createdAt: "createdAt",
      updatedAt: "updatedAt",
      ipAddress: "ipAddress",
      userAgent: "userAgent",
      userId: "userId",
      realm: "realm",
      mfaVerifiedAt: "mfaVerifiedAt",
    },
  },
  account: {
    exportName: "accounts",
    tableName: "accounts",
    table: accounts,
    fields: {
      id: "id",
      accountId: "accountId",
      providerId: "providerId",
      userId: "userId",
      accessToken: "accessToken",
      refreshToken: "refreshToken",
      idToken: "idToken",
      accessTokenExpiresAt: "accessTokenExpiresAt",
      refreshTokenExpiresAt: "refreshTokenExpiresAt",
      scope: "scope",
      password: "password",
      createdAt: "createdAt",
      updatedAt: "updatedAt",
    },
  },
  verification: {
    exportName: "verifications",
    tableName: "verifications",
    table: verifications,
    fields: {
      id: "id",
      identifier: "identifier",
      value: "value",
      expiresAt: "expiresAt",
      createdAt: "createdAt",
      updatedAt: "updatedAt",
    },
  },
  rateLimit: {
    exportName: "rateLimits",
    tableName: "rate_limits",
    table: rateLimits,
    fields: {
      id: "id",
      key: "key",
      count: "count",
      lastRequest: "lastRequest",
    },
  },
  twoFactor: {
    exportName: "twoFactors",
    tableName: "two_factors",
    table: twoFactors,
    fields: {
      id: "id",
      secret: "secret",
      backupCodes: "backupCodes",
      userId: "userId",
      verified: "verified",
      failedVerificationCount: "failedVerificationCount",
      lockedUntil: "lockedUntil",
    },
  },
} as const;

export const betterAuthAdapterSchema = {
  user: users,
  session: sessions,
  account: accounts,
  verification: verifications,
  rateLimit: rateLimits,
  twoFactor: twoFactors,
} as const;
